name: Build

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: npm ci
      - name: Build
        uses: npm run build

