name: Build

on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build

